version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag_backend
    environment:
      - DATA_DIR=/app/data/docs
      - MODEL_DIR=/app/llm_models
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./llm_models:/app/llm_models
    ports:
      - "8000:8000"
    command: uvicorn backend.server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - VITE_API_URL=http://localhost:8000